### ISSUE TITLE
replace factom.org with factom.com

### ISSUE THREAD

**Issue by davebooi** [yeahoffline/CryptoDomainBlock#2]

**Comment by blockkeeper** [comment]
factom.org -> redirects to factom.com. 
Added both tlds to the whitelist. 

Commit d9e60836592d01780f6f51c808d0eaa2b8ad7135

Thank you

**Comment by yeahoffline** [comment]
factom.org redirects to factom.com. Added both tlds to the whitelist. 

Commit d9e60836592d01780f6f51c808d0eaa2b8ad7135

Thank you !
