### ISSUE TITLE
mymọnero.com

### ISSUE THREAD

**Issue by davebooi** [yeahoffline/CryptoDomainBlock#3]
mymọnero.com still works (notice the ọ)

Reference discussion [here](https://www.reddit.com/r/Monero/comments/71jfk2/how_much_does_it_cost_to_scam_a_monero_user_about/)

**Comment by yeahoffline** [comment]
well mymọnero.com translates to xn--mymnero-ex4c.com so the whitelist is not able to match the result.

**Comment by yeahoffline** [comment]
change: b4f31029224a8ace42934dc695668feb8a2a90a5

you feel like testing and providing feedback? =)
